import { GoogleGenAI, Schema } from "@google/genai";

let genAIInstance: GoogleGenAI | null = null;

export const getGeminiClient = (): GoogleGenAI => {
  let apiKey = '';
  if (typeof window !== 'undefined') {
    apiKey = localStorage.getItem('USER_GEMINI_API_KEY') || "";
  }
  if (!apiKey) {
    apiKey = process.env.API_KEY || process.env.GEMINI_API_KEY || "";
  }
  if (!apiKey) {
    throw new Error("Gemini API Key is missing. Please set it in your environment settings.");
  }
  
  // Create a new instance every time to ensure it picks up changes from localStorage
  return new GoogleGenAI({ apiKey });
};

// Architecture heavily optimized towards Free Tier constraints:
export const getModelConfigs = () => {
  if (typeof window !== 'undefined') {
    const customKey = localStorage.getItem('USER_GEMINI_API_KEY');
    let customModel = localStorage.getItem('CUSTOM_USER_MODEL');
    if (customModel === 'gemini-2.5-flash-lite' || customModel === 'gemini-2.0-flash-lite-preview-02-05' || customModel === 'gemini-2.5-flash' || customModel === 'gemini-flash-latest' || customModel === 'gemini-1.5-flash') {
       customModel = 'gemini-3.5-flash';
    }
    if (customKey && customModel) {
      return {
        strategist: customModel,
        outline: customModel,
        writer: customModel,
        review: customModel,
        image: "gemini-3.5-flash" // Free-tier fallbacks will handle images
      };
    }
  }
  
  return {
    strategist: "gemini-3.5-flash", 
    outline: "gemini-3.5-flash",
    writer: "gemini-3.5-flash", 
    review: "gemini-3.5-flash",
    image: "gemini-3.5-flash"
  };
};

// Kept for type backwards compatibility in code, use getModelConfigs() directly at runtime
export const MODEL_CONFIGS = {
  strategist: "gemini-3.5-flash",
  outline: "gemini-3.5-flash",
  writer: "gemini-3.5-flash",
  review: "gemini-3.5-flash",
  image: "gemini-3.5-flash"
};

export class GeminiService {
  /**
   * Unified interface for hitting Gemini endpoints with enforced structured JSON.
   */
  static async requestStructured<T>(
    modelType: keyof ReturnType<typeof getModelConfigs>,
    prompt: string, 
    schema: Schema, 
    retries = 2
  ): Promise<T> {
    const targetModel = getModelConfigs()[modelType];
    const ai = getGeminiClient();
    
    let lastError: any;
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const response = await ai.models.generateContent({
          model: targetModel,
          contents: prompt,
          config: {
            responseMimeType: "application/json",
            responseSchema: schema,
            temperature: 0.5, 
          }
        });

        if (response.text) {
          return JSON.parse(response.text) as T;
        }
        throw new Error("Empty response body from model.");
      } catch (error: any) {
        console.error(`[GeminiService] attempt ${attempt} failed on ${modelType}:`, error);
        lastError = error;
      }
    }
    throw lastError || new Error(`Max retries exceeded for model: ${modelType}`);
  }

  /**
   * Unstructured fast text request
   */
  static async requestText(modelType: keyof ReturnType<typeof getModelConfigs>, prompt: string, retries = 1): Promise<string> {
    const targetModel = getModelConfigs()[modelType];
    const ai = getGeminiClient();
    let lastError: any;
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const response = await ai.models.generateContent({
          model: targetModel,
          contents: prompt
        });

        if (response.text) {
          return response.text.trim();
        }
      } catch (error: any) {
        console.error(`[GeminiService] text attempt ${attempt} failed on ${modelType}:`, error);
        lastError = error;
      }
    }
    throw lastError || new Error("Max text retries exceeded");
  }

  static async requestImage(prompt: string, editImageUrl?: string): Promise<string> {
    try {
      const ai = getGeminiClient();
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: prompt,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "9:16",
          },
        },
      });

      for (const part of response.candidates?.[0]?.content?.parts || []) {
        // Find the image part, do not assume it is the first part.
        if (part.inlineData) {
          const base64EncodeString: string = part.inlineData.data;
          return `data:image/jpeg;base64,${base64EncodeString}`;
        }
      }
      throw new Error("No image generated by Gemini API");
    } catch (e: any) {
      console.warn('Image generation failed, falling back to placeholder', e);
      // Fallback
      const seed = Math.floor(Math.random() * 1000000);
      const encodedPrompt = encodeURIComponent(prompt);
      return `https://image.pollinations.ai/prompt/${encodedPrompt}?width=800&height=1200&seed=${seed}&nologo=true`;
    }
  }
}
